### ISSUE TITLE
Is _build supposed to be in repo source tree?

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#6]
I just noticed the [_build](https://github.com/SpeQtral/etsi-qkd-api/tree/master/docsrc/_build) directory has crept into the repository versioning. I presume that is should be an ephemeral output directory that is made during documentation building. A production doc version lives [here](https://github.com/SpeQtral/etsi-qkd-api/tree/master/docs), right?

If so, clean it up by removing the files...don't worry about cleaning the git file history, just leave it in there.

Also, maybe add to a `.gitignore` so it doesn't get sucked up in the future?

**Comment by ajrheng** [comment]
Cleaned up by removing ``docsrc/_build`` from master. To clarify, ``docsrc`` is where the source files for Sphinx documentation are contained. docs is where github-pages actually accesses the HTML files, so after building with ``make html`` in ``docsrc``, copy and paste the files from ``docsrc/_build/html`` over to ``docs`` so that it shows on github-pages.
